// js/config.js
export const translations = {
    ru: {
        siteTitle: "Персональный сайт Тимур Якушев",
        headerTitle: "Тимур Якушев",
        headerTagline: "задаю глупые вопросы умным людям",
        headerSubtitle: "Технический директор | Team Lead AQA | Эксперт в автоматизации и создании IT-команд",
        contactMeButton: "Связаться со мной",
        aboutTitle: "Моя экспертиза",
        caseStudyTitle: "Ключевой проект: Архитектура автотестов",
        caseStudyTaskLabel: "Задача:",
        caseStudyTaskText: "Обеспечить стабильность крупного мобильного приложения (1 млн+ пользователей) и многократно ускорить процесс регрессионного тестирования.",
        caseStudySolutionLabel: "Решение:",
        caseStudySolutionText: "Вместе с командой, которую я собрал и развивал, мы разработали и внедрили с нуля новую архитектуру UI-автотестов на <code>Kotlin</code> и <code>Kaspresso</code>. В основе лежит паттерн <code>Page Object</code> с интуитивно понятным интерфейсом, позволяющий собирать тесты как конструктор. Я подготовил подробную документацию, что сократило время входа в проект для новых специалистов до нескольких дней.",
        caseStudyResultsLabel: "Результаты:",
        caseStudyResult1: "Покрытие тестами достигло 80%.",
        caseStudyResult2: "Время полного регресса сократилось до 15 минут (при 400+ UI-тестах).",
        caseStudyResult3: "0 критичных инцидентов, затронувших пользователей, за последние 4 года.",
        caseStudyResult4: "Команда выросла с 1 до 7 человек, каждый из которых успешно развивается и показывает высокие результаты.",
        aboutP1: "Сочетаю глубокие технические навыки с опытом управления. Специализируюсь на создании высокоэффективных IT-команд и построении сложных процессов с нуля.",
        aboutP2: "За 7 лет в IT прошел путь от инженера по тестированию до руководителя команды в Ozon. Работал в качестве вендора для Microsoft и Smartsheet. Моя цель — находить элегантные технические решения для сложных бизнес-задач.",
        servicesTitle: "Услуги",
        servicesP1: "Если у вас есть идея, но вы не знаете, как ее реализовать, — приходите. Я помогу вам с технической экспертизой, соберу команду или лично разработаю решение для вашего продукта.",
        resumeTitle: "Карьерный путь",
        resumeP1: "Резюме тут",
        downloadResumeButton: "Скачать полное резюме (PDF)",
        contactsTitle: "Контакты",
        contactsP1: "Готов обсудить ваш проект или ответить на вопросы.",
        contactEmail: "Email",
        contactLinkedIn: "LinkedIn",
        contactGitHub: "GitHub",
        contactTelegram: "Telegram",
        terminalWindowTitle: "Терминал", 
        terminalTitle: "Терминал", 
        terminalPromptUser: "guest",
        terminalPromptHost: "timur-yakushev.dev",
        terminalWelcome: "Добро пожаловать в мой интерактивный терминал!\nВведите 'help' для списка команд.",
        terminalHelpIntro: "Доступные команды:",
        terminalCmdHelp: "help          - Показать это сообщение помощи",
        terminalCmdAbout: "about         - Узнать больше обо мне и моей экспертизе",
        terminalCmdProject: "project       - Информация о ключевом проекте",
        terminalCmdServices: "services      - Какие услуги я предлагаю",
        terminalCmdResume: "resume        - Краткая информация о карьерном пути",
        terminalCmdContacts: "contacts      - Как со мной связаться",
        terminalCmdTheme: "theme         - Переключить светлую/темную тему",
        terminalCmdLang: "lang [ru|en|sr] - Сменить язык сайта (например, lang en)",
        terminalCmdClear: "clear         - Очистить экран терминала",
        terminalCmdNotFound: "Команда не найдена: ",
        settingsPanelTitle: "Настройки",
        settingsLangTitle: "Язык",
        settingsThemeTitle: "Тема",
        settingsLangRu: "Русский",
        settingsLangEn: "English",
        settingsLangSr: "Српски",
        settingsThemeLight: "Светлая",
        settingsThemeDark: "Темная"
    },
    en: {
        siteTitle: "Personal Website Timur Yakushev",
        headerTitle: "Timur Yakushev",
        headerTagline: "asking smart people silly questions",
        headerSubtitle: "CTO | AQA Android Team Lead | Automation & IT Team Building Expert",
        caseStudyTitle: "Key Project: Autotest Architecture",
        caseStudyTaskLabel: "Task:",
        caseStudyTaskText: "Ensure the stability of a large mobile application (1M+ users) and significantly speed up the regression testing process.",
        caseStudySolutionLabel: "Solution:",
        caseStudySolutionText: "Together with the team I assembled and nurtured, we developed and implemented a new UI autotest architecture from scratch using <code>Kotlin</code> and <code>Kaspresso</code>. It's based on the <code>Page Object</code> pattern with an intuitive interface, allowing tests to be assembled like a constructor. I prepared detailed documentation, reducing onboarding time for new specialists to a few days.",
        caseStudyResultsLabel: "Results:",
        caseStudyResult1: "Test coverage reached 80%.",
        caseStudyResult2: "Full regression time reduced to 15 minutes (for 400+ UI tests).",
        caseStudyResult3: "0 critical user-affecting incidents in the last 4 years.",
        caseStudyResult4: "The team grew from 1 to 7 people, each developing successfully and showing high results.",
        contactMeButton: "Contact Me",
        aboutTitle: "My Expertise",
        aboutP1: "I combine deep technical skills with management experience. I specialize in creating highly effective IT teams and building complex processes from scratch.",
        aboutP2: "In 7 years in IT, I've grown from a test engineer to a team leader at Ozon. Worked as a vendor for Microsoft and Smartsheet. My goal is to find elegant technical solutions for complex business tasks.",
        servicesTitle: "Services",
        servicesP1: "If you have an idea but don't know how to implement it, come to me. I will help you with technical expertise, assemble a team, or personally develop a solution for your product.",
        resumeTitle: "Career Path",
        resumeP1: "My CV",
        downloadResumeButton: "Download CV (PDF)",
        contactsTitle: "Contacts",
        contactsP1: "Ready to discuss your project or answer questions.",
        contactEmail: "Email",
        contactLinkedIn: "LinkedIn",
        contactGitHub: "GitHub",
        contactTelegram: "Telegram",
        terminalWindowTitle: "Terminal",
        terminalTitle: "Terminal",
        terminalPromptUser: "guest",
        terminalPromptHost: "timur-yakushev.dev",
        terminalWelcome: "Welcome to my interactive terminal!\nType 'help' for a list of commands.",
        terminalHelpIntro: "Available commands:",
        terminalCmdHelp: "help          - Show this help message",
        terminalCmdAbout: "about         - Learn more about me and my expertise",
        terminalCmdProject: "project       - Information about the key project",
        terminalCmdServices: "services      - What services I offer",
        terminalCmdResume: "resume        - Brief information about my career path",
        terminalCmdContacts: "contacts      - How to contact me",
        terminalCmdTheme: "theme         - Toggle light/dark theme",
        terminalCmdLang: "lang [ru|en|sr] - Change site language (e.g., lang en)",
        terminalCmdClear: "clear         - Clear the terminal screen",
        terminalCmdNotFound: "Command not found: ",
        settingsPanelTitle: "Settings",
        settingsLangTitle: "Language",
        settingsThemeTitle: "Theme",
        settingsLangRu: "Русский", 
        settingsLangEn: "English",
        settingsLangSr: "Српски",
        settingsThemeLight: "Light",
        settingsThemeDark: "Dark"
    },
    sr: {
        siteTitle: "Lična veb stranica Timur Jakušev",
        headerTitle: "Timur Jakušev",
        headerTagline: "postavljam pametnim ljudima glupa pitanja",
        headerSubtitle: "Tehnički direktor | Vođa AQA Android tima | Stručnjak za automatizaciju i izgradnju IT timova",
        caseStudyTitle: "Ključni projekat: Arhitektura auto-testova",
        caseStudyTaskLabel: "Zadatak:",
        caseStudyTaskText: "Osigurati stabilnost velike mobilne aplikacije (1M+ korisnika) i značajno ubrzati proces regresionog testiranja.",
        caseStudySolutionLabel: "Rešenje:",
        caseStudySolutionText: "Zajedno sa timom koji sam okupio i razvijao, razvili smo i implementirali novu arhitekturu UI auto-testova od nule koristeći <code>Kotlin</code> i <code>Kaspresso</code>. Zasnovana je na <code>Page Object</code> modelu sa intuitivnim interfejsom, omogućavajući sastavljanje testova kao konstruktor. Pripremio sam detaljnu dokumentaciju, smanjujući vreme uvođenja novih stručnjaka na nekoliko dana.",
        caseStudyResultsLabel: "Rezultati:",
        caseStudyResult1: "Pokrivenost testovima dostigla 80%.",
        caseStudyResult2: "Vreme pune regresije smanjeno na 15 minuta (za 400+ UI testova).",
        caseStudyResult3: "0 kritičnih incidenata koji su uticali na korisnike u poslednje 4 godine.",
        caseStudyResult4: "Tim je porastao sa 1 na 7 ljudi, od kojih se svaki uspešno razvija i pokazuje visoke rezultate.",
        contactMeButton: "Kontaktirajte me",
        aboutTitle: "Moja stručnost",
        aboutP1: "Kombinujem duboke tehničke veštine sa iskustvom u upravljanju. Specijalizovan sam za stvaranje visoko efikasnih IT timova i izgradnju složenih procesa od nule.",
        aboutP2: "Za 7 godina u IT-u, prešao sam put od inženjera za testiranje do vođe tima u Ozon-u. Radio sam kao dobavljač za Microsoft i Smartsheet. Moj cilj je pronalaženje elegantnih tehničkih rešenja za složene poslovne zadatke.",
        servicesTitle: "Usluge",
        servicesP1: "Ako imate ideju, ali ne znate kako da je realizujete, obratite mi se. Pomoći ću vam tehničkom ekspertizom, okupiti tim ili lično razviti rešenje za vaš proizvod.",
        resumeTitle: "Karijerni put",
        resumeP1: "CV",
        downloadResumeButton: "Preuzmite kompletan rezime (PDF)",
        contactsTitle: "Kontakti",
        contactsP1: "Spreman sam da razgovaram o vašem projektu ili odgovorim na pitanja.",
        contactEmail: "Imejl",
        contactLinkedIn: "LinkedIn",
        contactGitHub: "GitHub",
        contactTelegram: "Telegram",
        terminalWindowTitle: "Terminal",
        terminalTitle: "Terminal",
        terminalPromptUser: "guest",
        terminalPromptHost: "timur-yakushev.dev",
        terminalWelcome: "Dobrodošli u moj interaktivni terminal!\nUnesite 'help' za listu komandi.",
        terminalHelpIntro: "Dostupne komande:",
        terminalCmdHelp: "help          - Prikaži ovu poruku pomoći",
        terminalCmdAbout: "about         - Saznajte više o meni i mojoj stručnosti",
        terminalCmdProject: "project       - Informacije o ključnom projektu",
        terminalCmdServices: "services      - Koje usluge nudim",
        terminalCmdResume: "resume        - Kratke informacije o mom karijernom putu",
        terminalCmdContacts: "contacts      - Kako da me kontaktirate",
        terminalCmdTheme: "theme         - Prebaci svetlu/tamnu temu",
        terminalCmdLang: "lang [ru|en|sr] - Promeni jezik sajta (npr. lang en)",
        terminalCmdClear: "clear         - Obriši ekran terminala",
        terminalCmdNotFound: "Komanda nije pronađena: ",
        settingsPanelTitle: "Podešavanja",
        settingsLangTitle: "Jezik",
        settingsThemeTitle: "Tema",
        settingsLangRu: "Ruski", 
        settingsLangEn: "English",
        settingsLangSr: "Srpski",
        settingsThemeLight: "Svetla",
        settingsThemeDark: "Tamna"
    }
};