// js/config.js
export const translations = {
    ru: {
        siteTitle: "Персональный сайт Тимур Якушев",
        headerTitle: "Тимур Якушев",
        headerTagline: "задаю глупые вопросы умным людям",
        headerSubtitle: "Технический директор | Team Lead AQA | Эксперт в автоматизации и создании IT-команд",
        contactMeButton: "Связаться со мной",
        aboutTitle: "Моя экспертиза",
        caseStudyTitle: "Ключевой проект: Архитектура автотестов",
        caseStudyTaskLabel: "Задача:",
        caseStudyTaskText: "Обеспечить стабильность крупного мобильного приложения (1 млн+ пользователей) и многократно ускорить процесс регрессионного тестирования.",
        caseStudySolutionLabel: "Решение:",
        caseStudySolutionText: "Вместе с командой, которую я собрал и развивал, мы разработали и внедрили с нуля новую архитектуру UI-автотестов на <code>Kotlin</code> и <code>Kaspresso</code>. В основе лежит паттерн <code>Page Object</code> с интуитивно понятным интерфейсом, позволяющий собирать тесты как конструктор. Я подготовил подробную документацию, что сократило время входа в проект для новых специалистов до нескольких дней.",
        caseStudyResultsLabel: "Результаты:",
        caseStudyResult1: "Покрытие тестами достигло 80%.",
        caseStudyResult2: "Время полного регресса сократилось до 15 минут (при 400+ UI-тестах).",
        caseStudyResult3: "0 критичных инцидентов, затронувших пользователей, за последние 4 года.",
        caseStudyResult4: "Команда выросла с 1 до 7 человек, каждый из которых успешно развивается и показывает высокие результаты.",
        aboutP1: "Сочетаю глубокие технические навыки с опытом управления. Специализируюсь на создании высокоэффективных IT-команд и построении сложных процессов с нуля.",
        aboutP2: "За 7 лет в IT прошел путь от инженера по тестированию до руководителя команды в Ozon. Работал в качестве вендора для Microsoft и Smartsheet. Моя цель — находить элегантные технические решения для сложных бизнес-задач.",
        servicesTitle: "Услуги",
        servicesP1: "Если у вас есть идея, но вы не знаете, как ее реализовать, — приходите. Я помогу вам с технической экспертизой, соберу команду или лично разработаю решение для вашего продукта.",
        resumeTitle: "Карьерный путь",
        resumeP1: "Резюме тут",
        downloadResumeButton: "Скачать полное резюме (PDF)",
        contactsTitle: "Контакты",
        contactsP1: "Готов обсудить ваш проект или ответить на вопросы.",
        contactEmail: "Email",
        contactLinkedIn: "LinkedIn",
        contactGitHub: "GitHub",
        contactTelegram: "Telegram",
        terminalWindowTitle: "Терминал", 
        terminalTitle: "Терминал", 
        terminalPromptUser: "guest",
        terminalPromptHost: "timur-yakushev.dev",
        terminalWelcome: "Добро пожаловать в мой интерактивный терминал!\nВведите 'help' для списка команд.",
        terminalHelpIntro: "Доступные команды:",
        terminalCmdHelp: "help          - Показать это сообщение помощи",
        terminalCmdAbout: "about         - Узнать больше обо мне и моей экспертизе",
        terminalCmdProject: "project       - Информация о ключевом проекте",
        terminalCmdServices: "services      - Какие услуги я предлагаю",
        terminalCmdResume: "resume        - Краткая информация о карьерном пути",
        terminalCmdContacts: "contacts      - Как со мной связаться",
        terminalCmdTheme: "theme         - Переключить светлую/темную тему",
        terminalCmdLang: "lang [ru|en|sr] - Сменить язык сайта (например, lang en)",
        terminalCmdClear: "clear         - Очистить экран терминала",
        terminalCmdNotFound: "Команда не найдена: ",
        settingsPanelTitle: "Настройки",
        settingsLangTitle: "Язык",
        settingsThemeTitle: "Тема",
        settingsLangRu: "Русский",
        settingsLangEn: "English",
        settingsLangSr: "Српски",
        settingsThemeLight: "Светлая",
        settingsThemeDark: "Темная"
    },
    en: {
        siteTitle: "Personal Website Timur Yakushev",
        headerTitle: "Timur Yakushev",
        headerTagline: "asking smart people silly questions",
        headerSubtitle: "CTO | AQA Android Team Lead | Automation & IT Team Building Expert",
        caseStudyTitle: "Key Project: Autotest Architecture",
        caseStudyTaskLabel: "Task:",
        caseStudyTaskText: "Ensure the stability of a large mobile application (1M+ users) and significantly speed up the regression testing process.",
        caseStudySolutionLabel: "Solution:",
        caseStudySolutionText: "Together with the team I assembled and nurtured, we developed and implemented a new UI autotest architecture from scratch using <code>Kotlin</code> and <code>Kaspresso</code>. It's based on the <code>Page Object</code> pattern with an intuitive interface, allowing tests to be assembled like a constructor. I prepared detailed documentation, reducing onboarding time for new specialists to a few days.",
        caseStudyResultsLabel: "Results:",
        caseStudyResult1: "Test coverage reached 80%.",
        caseStudyResult2: "Full regression time reduced to 15 minutes (for 400+ UI tests).",
        caseStudyResult3: "0 critical user-affecting incidents in the last 4 years.",
        caseStudyResult4: "The team grew from 1 to 7 people, each developing successfully and showing high results.",
        contactMeButton: "Contact Me",
        aboutTitle: "My Expertise",
        aboutP1: "I combine deep technical skills with management experience. I specialize in creating highly effective IT teams and building complex processes from scratch.",
        aboutP2: "In 7 years in IT, I've grown from a test engineer to a team leader at Ozon. Worked as a vendor for Microsoft and Smartsheet. My goal is to find elegant technical solutions for complex business tasks.",
        servicesTitle: "Services",
        servicesP1: "If you have an idea but don't know how to implement it, come to me. I will help you with technical expertise, assemble a team, or personally develop a solution for your product.",
        resumeTitle: "Career Path",
        resumeP1: "My CV",
        downloadResumeButton: "Download CV (PDF)",
        contactsTitle: "Contacts",
        contactsP1: "Ready to discuss your project or answer questions.",
        contactEmail: "Email",
        contactLinkedIn: "LinkedIn",
        contactGitHub: "GitHub",
        contactTelegram: "Telegram",
        terminalWindowTitle: "Terminal",
        terminalTitle: "Terminal",
        terminalPromptUser: "guest",
        terminalPromptHost: "timur-yakushev.dev",
        terminalWelcome: "Welcome to my interactive terminal!\nType 'help' for a list of commands.",
        terminalHelpIntro: "Available commands:",
        terminalCmdHelp: "help          - Show this help message",
        terminalCmdAbout: "about         - Learn more about me and my expertise",
        terminalCmdProject: "project       - Information about the key project",
        terminalCmdServices: "services      - What services I offer",
        terminalCmdResume: "resume        - Brief information about my career path",
        terminalCmdContacts: "contacts      - How to contact me",
        terminalCmdTheme: "theme         - Toggle light/dark theme",
        terminalCmdLang: "lang [ru|en|sr] - Change site language (e.g., lang en)",
        terminalCmdClear: "clear         - Clear the terminal screen",
        terminalCmdNotFound: "Command not found: ",
        settingsPanelTitle: "Settings",
        settingsLangTitle: "Language",
        settingsThemeTitle: "Theme",
        settingsLangRu: "Русский", 
        settingsLangEn: "English",
        settingsLangSr: "Српски",
        settingsThemeLight: "Light",
        settingsThemeDark: "Dark"
    },
    sr: {
        siteTitle: "Лична веб страница Тимур Јакушев",
        headerTitle: "Тимур Јакушев",
        headerTagline: "постављам паметним људима глупа питања",
        headerSubtitle: "Технички директор | Вођа АКА Андроид тима | Стручњак за аутоматизацију и изградњу ИТ тимова",
        caseStudyTitle: "Кључни пројекат: Архитектура ауто-тестова",
        caseStudyTaskLabel: "Задатак:",
        caseStudyTaskText: "Осигурати стабилност велике мобилне апликације (1М+ корисника) и значајно убрзати процес регресионог тестирања.",
        caseStudySolutionLabel: "Решење:",
        caseStudySolutionText: "Заједно са тимом који сам окупио и развијао, развили смо и имплементирали нову архитектуру УИ ауто-тестова од нуле користећи <code>Котлин</code> и <code>Каспрессо</code>. Заснована је на <code>Page Object</code> шаблону са интуитивним интерфејсом, омогућавајући састављање тестова као конструктор. Припремио сам детаљну документацију, смањујући време увођења нових стручњака на неколико дана.",
        caseStudyResultsLabel: "Резултати:",
        caseStudyResult1: "Покривеност тестовима достигла 80%.",
        caseStudyResult2: "Време пуне регресије смањено на 15 минута (за 400+ УИ тестова).",
        caseStudyResult3: "0 критичних инцидената који су утицали на кориснике у последње 4 године.",
        caseStudyResult4: "Тим је порастао са 1 на 7 људи, од којих се сваки успешно развија и показује високе резултате.",
        contactMeButton: "Контактирајте ме",
        aboutTitle: "Моја стручност",
        aboutP1: "Комбинујем дубоке техничке вештине са искуством у управљању. Специјализован сам за стварање високо ефикасних ИТ тимова и изградњу сложених процеса од нуле.",
        aboutP2: "За 7 година у ИТ-у, прешао сам пут од инжењера за тестирање до вође тима у Ozon-у. Радио сам као добављач за Microsoft и Smartsheet. Мој циљ је проналажење елегантних техничких решења за сложене пословне задатке.",
        servicesTitle: "Услуге",
        servicesP1: "Ако имате идеју, али не знате како да је реализујете, обратите ми се. Помоћи ћу вам техничком експертизом, окупити тим или лично развити решење за ваш производ.",
        resumeTitle: "Каријерни пут",
        resumeP1: "Овде можете поставити 2-3 кључне фазе ваше каријере или везу до детаљнијег резимеа.",
        downloadResumeButton: "Преузмите комплетан резиме (ПДФ)",
        contactsTitle: "Контакти",
        contactsP1: "Спреман сам да разговарам о вашем пројекту или одговорим на питања.",
        contactEmail: "Имејл",
        contactLinkedIn: "LinkedIn",
        contactGitHub: "GitHub",
        contactTelegram: "Telegram",
        terminalWindowTitle: "Терминал",
        terminalTitle: "Терминал",
        terminalPromptUser: "guest",
        terminalPromptHost: "timur-yakushev.dev",
        terminalWelcome: "Добродошли у мој интерактивни терминал!\nУнесите 'help' за листу команди.",
        terminalHelpIntro: "Доступне команде:",
        terminalCmdHelp: "help          - Прикажи ову поруку помоћи",
        terminalCmdAbout: "about         - Сазнајте више о мени и мојој стручности",
        terminalCmdProject: "project       - Информације о кључном пројекту",
        terminalCmdServices: "services      - Које услуге нудим",
        terminalCmdResume: "resume        - Кратке информације о мом каријерном путу",
        terminalCmdContacts: "contacts      - Како да ме контактирате",
        terminalCmdTheme: "theme         - Пребаци светлу/тамну тему",
        terminalCmdLang: "lang [ru|en|sr] - Промени језик сајта (нпр. lang en)",
        terminalCmdClear: "clear         - Обриши екран терминала",
        terminalCmdNotFound: "Команда није пронађена: ",
        settingsPanelTitle: "Подешавања",
        settingsLangTitle: "Језик",
        settingsThemeTitle: "Тема",
        settingsLangRu: "Русскии",
        settingsLangEn: "English",
        settingsLangSr: "Српски",
        settingsThemeLight: "Светла",
        settingsThemeDark: "Тамнa"
    }
};